name: griptape
services:
  web:
    read_only: False
    image: griptape-web
    environment:
      - DISABLE_AUTH=${DISABLE_AUTH:-False}
      - DATADOG_ENABLED=${DATADOG_ENABLED:-False}
    depends_on:
      - release
      - redis
      - minio
    ports:
      - "${WEB_API_PORT}:${PORT}"
      - "${WEB_FRONTEND_PORT}:5173"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCAL_EXECUTION_VOLUME_MOUNT:-./runtime}:/runtime
    env_file: .env
  workers:
    read_only: False
    image: griptape-workers
    environment:
      - DATADOG_ENABLED=${DATADOG_ENABLED:-False}
    depends_on:
      - release
      - redis
      - minio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCAL_EXECUTION_VOLUME_MOUNT:-./runtime}:/runtime
    env_file: .env
  scheduler:
    read_only: False
    image: griptape-scheduler
    environment:
      - DATADOG_ENABLED=${DATADOG_ENABLED:-False}
    depends_on:
      - release
      - redis
      - minio
    env_file: .env
    restart: on-failure:3
  release:
    read_only: False
    image: griptape-release
    environment:
      - DATADOG_ENABLED=${DATADOG_ENABLED:-False}
    depends_on:
      - postgres
      - pgvector
      - minio
    env_file: .env
  postgres:
    read_only: false
    image: postgres:16@sha256:6b841c8f6a819884207402f1209a8116844365df15fca8cf556fc54a24c70800
    hostname: $RESOURCE_DB_HOSTNAME
    ports:
      - "54320:${RESOURCE_DB_PORT}"
    env_file: .env
    environment:
      POSTGRES_USER: $RESOURCE_DB_USER
      POSTGRES_PASSWORD: $RESOURCE_DB_PASSWORD
      POSTGRES_DB: $RESOURCE_DB
  pgvector:
    read_only: false
    image: pgvector/pgvector:pg16@sha256:97293194fca020b1db13d5957fff318780c43b6ef898540ff4b67b2b6524bd6b
    hostname: $VECTOR_DB_HOSTNAME
    ports:
      - "54321:${VECTOR_DB_PORT}"
    env_file: .env
    environment:
      POSTGRES_USER: $VECTOR_DB_USER
      POSTGRES_PASSWORD: $VECTOR_DB_PASSWORD
      POSTGRES_DB: $VECTOR_DB
  redis:
    read_only: false
    image: redis:7-alpine@sha256:7635b0bfdd7dd8552b4b31d6541fef07b734614045b45a52fd5cc27c9dada9e2
    hostname: $REDIS_HOSTNAME
    ports:
      - "${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel $REDIS_LOG_LEVEL --requirepass $REDIS_PASSWORD
    env_file: .env
  minio:
    read_only: false
    image: docker.io/bitnami/minio@sha256:ba9f3b4b0b008de80b7d1d7a26c336fed3141ddf47788b7a790fc66292132e21
    hostname: ${MINIO_HOSTNAME:-minio}
    ports:
      - "${MINIO_API_PORT_NUMBER:-9000}:9000"
      - "${MINIO_CONSOLE_PORT_NUMBER:-9001}:9001"
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_SERVER_ACCESS_KEY:-minioadmin}
      - MINIO_SERVER_SECRET_KEY=${MINIO_SERVER_SECRET_KEY:-minioadmin}
volumes:
  redis_data:
